name GitHub-Profile-3D-Contrib

on
  schedule # 0300 JST == 1800 UTC
    - cron 0 18   
  workflow_dispatch

permissions
  contents write

jobs
  build
    runs-on ubuntu-latest
    name generate-github-profile-3d-contrib
    steps
      - uses actionscheckout@v5
      - uses yoshi389111github-profile-3d-contrib@latest
        env
          GITHUB_TOKEN ${{ secrets.GITHUB_TOKEN }}
          USERNAME ${{ github.jungse8609 }}
      - name Commit & Push
        run 
          git config user.name jungse8609
          git config user.email jungse8609@gmail.com
          git add -A .
          if git commit -m generated; then
            git push
          fi
